INSERT INTO `OBRA` VALUES (1,14000,'Riego Nocturno',2019,'Expresionismo abstracto','130x97',NULL,NULL,'Lienzo','Acrílica',NULL,NULL,NULL,'Pintura',1,NULL,NULL,NULL,NULL);
INSERT INTO `OBRA` VALUES (2,8500,'Pintura Errante',2019,'Expresionismo abstracto','130x97',NULL,NULL,'Lienzo','Acrílica',NULL,NULL,NULL,'Pintura',1,NULL,NULL,NULL,NULL);
INSERT INTO `OBRA` VALUES (3,10000,'Segundo Tiempo',2019,'Expresionismo abstracto','97x97',NULL,NULL,'Lienzo','Acrílica',NULL,NULL,NULL,'Pintura',1,NULL,NULL,NULL,NULL);
INSERT INTO `OBRA` VALUES (4,1210,'Europa',1989,'Neofiguración','76x56',NULL,NULL,'Metal','Litografía',NULL,NULL,NULL,'Pintura',2,NULL,NULL,NULL,NULL);
INSERT INTO `OBRA` VALUES (5,2060,'Éboli',2004,'Neofiguración','80x60',NULL,NULL,'Metal','AguaFuerte',NULL,NULL,NULL,'Pintura',2,NULL,NULL,NULL,NULL);
INSERT INTO `OBRA` VALUES (6,8470,'Caballero',1985,'Neofiguración','66x43x12','Acero cortén','Variada',NULL,NULL,NULL,NULL,NULL,'Escultura',2,NULL,NULL,NULL,NULL);
INSERT INTO `OBRA` VALUES (7,8020,'Melancolía',2018,'Pintura narrativa','153x205',NULL,NULL,'Papel','Acuarela',NULL,NULL,NULL,'Pintura',3,NULL,NULL,NULL,NULL);
INSERT INTO `OBRA` VALUES (8,3000,'Depresión en el camino',2020,'Pintura narrativa','135x175',NULL,NULL,'Papel','Acuarela',NULL,NULL,NULL,'Pintura',3,NULL,NULL,NULL,NULL);
INSERT INTO `OBRA` VALUES (9,1800,'La casa',2019,'Pintura narrativa','45x97',NULL,NULL,'Papel','Óleo',NULL,NULL,NULL,'Pintura',3,NULL,NULL,NULL,NULL);
INSERT INTO `OBRA` VALUES (10,5550,'La Gran Cena Española',1988,'Neo-Expresionista','200x300',NULL,NULL,'Papel','Pigmentos y látex',NULL,NULL,NULL,'Pintura',4,NULL,NULL,NULL,NULL);
INSERT INTO `OBRA` VALUES (11,7600,'Dos Postes',1987,'Neo-Expresionista','230x230',NULL,NULL,'Papel','Pintura industrial',NULL,NULL,NULL,'Pintura',4,NULL,NULL,NULL,NULL);
INSERT INTO `OBRA` VALUES (12,753753000,'Guernica',1937,'Cubismo','776x349',NULL,NULL,'Lienzo','Óleo',NULL,NULL,NULL,'Pintura',5,NULL,NULL,NULL,NULL);
INSERT INTO `OBRA` VALUES (13,14000000,'Autorretrato',1901,'Expresionismo','81x60',NULL,NULL,'Lienzo','Óleo',NULL,NULL,NULL,'Pintura',5,NULL,NULL,NULL,NULL);
INSERT INTO `OBRA` VALUES (14,8900,'La Familia',1972,'Abstracto','150x200',NULL,NULL,'Lienzo','Acrílico',NULL,NULL,NULL,'Pintura',6,NULL,NULL,NULL,NULL);
INSERT INTO `OBRA` VALUES (15,3000,'Automovilistas en el paisaje',1968,'Abstracto','160x111',NULL,NULL,'Lienzo','Acrílico',NULL,NULL,NULL,'Pintura',6,NULL,NULL,NULL,NULL);
INSERT INTO `OBRA` VALUES (16,1670,'The Apparition',1963,'Expresionismo','54x80',NULL,NULL,'Lienzo','Pintura al aceite',NULL,NULL,NULL,'Pintura',7,NULL,NULL,NULL,NULL);
INSERT INTO `OBRA` VALUES (17,1670,'Chaleco en el doblado',1971,'Surrealismo','82x65',NULL,NULL,'Lienzo','Óleo',NULL,NULL,NULL,'Pintura',8,NULL,NULL,NULL,NULL);
INSERT INTO `OBRA` VALUES (18,7800,'El contraluz',1971,'Surrealismo','60x40',NULL,NULL,'Tabla','Óleo',NULL,NULL,NULL,'Pintura',8,NULL,NULL,NULL,NULL);
INSERT INTO `OBRA` VALUES (19,1200,'Las Tuberías',1972,'Surrealismo','86x68',NULL,NULL,'Lienzo','Óleo',NULL,NULL,NULL,'Pintura',8,NULL,NULL,NULL,NULL);
INSERT INTO `OBRA` VALUES (20,NULL,'Retrato de D. Jesús Posada',1987,'Luminismo','80x125',NULL,NULL,'Lienzo','Óleo',NULL,NULL,NULL,'Pintura',9,NULL,NULL,NULL,NULL);
INSERT INTO `OBRA` VALUES (21,1000000000,'La noche estrellada',1889,'PostImpresionismo','74x92',NULL,NULL,'Lienzo','Óleo',NULL,NULL,NULL,'Pintura',10,NULL,NULL,NULL,NULL);
INSERT INTO `OBRA` VALUES (22,71500000,'Autorretrato',1889,'PostImpresionismo','65x54',NULL,NULL,'Lienzo','Óleo',NULL,NULL,NULL,'Pintura',10,NULL,NULL,NULL,NULL);
INSERT INTO `OBRA` VALUES (23,NULL,'Rose and Driftwood',1932,NULL,NULL,NULL,NULL,NULL,NULL,'Papel Fotográfico','Medición','Fuelle','Fotografía',11,NULL,NULL,NULL,NULL);
INSERT INTO `OBRA` VALUES (24,NULL,'Clearing Winter Storm',1937,NULL,NULL,NULL,NULL,NULL,NULL,'Papel Fotográfico','Medición','Fuelle','Fotografía',11,NULL,NULL,NULL,NULL);
INSERT INTO `OBRA` VALUES (25,NULL,'Ice on Ellery Lake',1941,NULL,NULL,NULL,NULL,NULL,NULL,'Papel Fotográfico','Medición','Fuelle','Fotografía',11,NULL,NULL,NULL,NULL);
INSERT INTO `OBRA` VALUES (26,NULL,'La muchacha afgana',1984,NULL,NULL,NULL,NULL,NULL,NULL,'Papel Fotográfico','Revelado','Analógica','Fotografía',12,NULL,NULL,NULL,NULL);
INSERT INTO `OBRA` VALUES (27,NULL,'Three Points',1939,'Surrealismo','140x190x95mm','Bronze','Variada',NULL,NULL,NULL,NULL,NULL,'Escultura',13,NULL,NULL,NULL,NULL);
INSERT INTO `OBRA` VALUES (28,NULL,'Stringed Figure',1938,'Surrealismo','273x343x197mm','Bronze and elastic string','Variada',NULL,NULL,NULL,NULL,NULL,'Escultura',13,NULL,NULL,NULL,NULL);
INSERT INTO `OBRA` VALUES (29,NULL,'Figure',1931,'Surrealismo','248x178x121mm','Beech','Variada',NULL,NULL,NULL,NULL,NULL,'Escultura',13,NULL,NULL,NULL,NULL);
INSERT INTO `OBRA` VALUES (30,3800,'Recicling Figure',1939,'Surrealismo','137x254x86mm','Bronze','Variada',NULL,NULL,NULL,NULL,NULL,'Escultura',13,NULL,NULL,NULL,NULL);
INSERT INTO `OBRA` VALUES (31,NULL,'Tormenta de arena',1987,NULL,NULL,NULL,NULL,NULL,NULL,'Papel Fotográfico','Revelado','Analógica','Fotografía',12,NULL,NULL,NULL,NULL);
