CREATE DEFINER = CURRENT_USER TRIGGER `galeriaArte`.`calcular_edad_artista` BEFORE INSERT ON `ARTISTA` FOR EACH ROW
BEGIN
  IF NEW.FechaNacimiento IS NOT NULL AND NEW.Edad IS NULL THEN
    SET NEW.Edad = YEAR(CURRENT_TIMESTAMP()) - YEAR(NEW.FechaNacimiento);
  END IF;
END
