CREATE DEFINER = CURRENT_USER TRIGGER `galeriaArte`.`ExclusividadObra_Ofrece` BEFORE INSERT ON `OFRECE` FOR EACH ROW
BEGIN
	DECLARE id INT;
    SELECT idOBRA INTO @id FROM MUESTRA WHERE idOBRA = NEW.idOBRA limit 1;
	IF (@id = NEW.idOBRA) THEN
		 SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Condición de exclusividad entre OFRECE y MUESTRA respecto OBRA';
    END IF;
END