-- MySQL Script generated by MySQL Workbench
-- Fri Feb  5 18:42:11 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema galeriaArte
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema galeriaArte
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `galeriaArte` DEFAULT CHARACTER SET utf8 ;
USE `galeriaArte` ;

-- -----------------------------------------------------
-- Table `galeriaArte`.`EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `galeriaArte`.`EMPLEADO` (
  `DNI` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Puesto` VARCHAR(45) NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `galeriaArte`.`SUBASTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `galeriaArte`.`SUBASTA` (
  `idSUBASTA` INT NOT NULL,
  `numObras` INT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idSUBASTA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `galeriaArte`.`ARTISTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `galeriaArte`.`ARTISTA` (
  `DNI` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `NumObras` INT NULL,
  `FechaNacimiento` DATE NULL,
  `Edad` INT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `galeriaArte`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `galeriaArte`.`CLIENTE` (
  `DNI` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `NumSocio` INT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `galeriaArte`.`OBRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `galeriaArte`.`OBRA` (
  `idOBRA` INT NOT NULL,
  `Precio` FLOAT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Año` INT NULL,
  `MovimientoArtistica` VARCHAR(45) NULL,
  `Dimensiones` VARCHAR(45) NULL,
  `Material` VARCHAR(45) NULL,
  `Herramienta` VARCHAR(45) NULL,
  `Superficie` VARCHAR(45) NULL,
  `TipoPintura` VARCHAR(45) NULL,
  `Papel` VARCHAR(45) NULL,
  `Metodo` VARCHAR(45) NULL,
  `TipoCamara` VARCHAR(45) NULL,
  `Tipo` VARCHAR(45) NULL,
  `ARTISTA_DNI` INT NULL,
  `CLIENTE_DNI` INT NULL,
  `PrecioInicialCompra` INT NULL,
  `PrecioFinalCompra` INT NULL,
  `SubastaVendida` INT NULL,
  PRIMARY KEY (`idOBRA`),
  INDEX `fk_OBRA_ARTISTA1_idx` (`ARTISTA_DNI` ASC) ,
  INDEX `fk_OBRA_CLIENTE1_idx` (`CLIENTE_DNI` ASC) ,
  INDEX `fk_OBRA_SUBASTA1_idx` (`SubastaVendida` ASC) ,
  CONSTRAINT `fk_OBRA_ARTISTA1`
    FOREIGN KEY (`ARTISTA_DNI`)
    REFERENCES `galeriaArte`.`ARTISTA` (`DNI`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_OBRA_CLIENTE1`
    FOREIGN KEY (`CLIENTE_DNI`)
    REFERENCES `galeriaArte`.`CLIENTE` (`DNI`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_OBRA_SUBASTA1`
    FOREIGN KEY (`SubastaVendida`)
    REFERENCES `galeriaArte`.`SUBASTA` (`idSUBASTA`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `galeriaArte`.`PREMIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `galeriaArte`.`PREMIO` (
  `idPREMIO` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Año` INT NULL,
  `idOBRA` INT NULL,
  PRIMARY KEY (`idPREMIO`),
  INDEX `fk_PREMIO_OBRA1_idx` (`idOBRA` ASC) ,
  CONSTRAINT `fk_PREMIO_OBRA1`
    FOREIGN KEY (`idOBRA`)
    REFERENCES `galeriaArte`.`OBRA` (`idOBRA`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `galeriaArte`.`EXPOSICION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `galeriaArte`.`EXPOSICION` (
  `idEXPOSICION` INT NOT NULL,
  `NumObras` INT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idEXPOSICION`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `galeriaArte`.`GALERIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `galeriaArte`.`GALERIA` (
  `idGALERIA` INT NOT NULL,
  `Aforo` INT NULL,
  `Ubicacion` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idGALERIA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `galeriaArte`.`MUESTRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `galeriaArte`.`MUESTRA` (
  `idOBRA` INT NOT NULL,
  `idEXPOSICION` INT NOT NULL,
  PRIMARY KEY (`idOBRA`, `idEXPOSICION`),
  INDEX `fk_OBRA_has_EXPOSICION_EXPOSICION1_idx` (`idEXPOSICION` ASC) ,
  INDEX `fk_OBRA_has_EXPOSICION_OBRA1_idx` (`idOBRA` ASC) ,
  CONSTRAINT `fk_OBRA_has_EXPOSICION_OBRA1`
    FOREIGN KEY (`idOBRA`)
    REFERENCES `galeriaArte`.`OBRA` (`idOBRA`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_OBRA_has_EXPOSICION_EXPOSICION1`
    FOREIGN KEY (`idEXPOSICION`)
    REFERENCES `galeriaArte`.`EXPOSICION` (`idEXPOSICION`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `galeriaArte`.`OFRECE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `galeriaArte`.`OFRECE` (
  `idOBRA` INT NOT NULL,
  `idSUBASTA` INT NOT NULL,
  PRIMARY KEY (`idOBRA`, `idSUBASTA`),
  INDEX `fk_OBRA_has_SUBASTA_SUBASTA1_idx` (`idSUBASTA` ASC) ,
  INDEX `fk_OBRA_has_SUBASTA_OBRA1_idx` (`idOBRA` ASC) ,
  CONSTRAINT `fk_OBRA_has_SUBASTA_OBRA1`
    FOREIGN KEY (`idOBRA`)
    REFERENCES `galeriaArte`.`OBRA` (`idOBRA`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_OBRA_has_SUBASTA_SUBASTA1`
    FOREIGN KEY (`idSUBASTA`)
    REFERENCES `galeriaArte`.`SUBASTA` (`idSUBASTA`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `galeriaArte`.`TRABAJA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `galeriaArte`.`TRABAJA` (
  `idGALERIA` INT NOT NULL,
  `dniEMPLEADO` INT NOT NULL,
  `FechaIni` DATE NOT NULL,
  `FechaFin` DATE NULL,
  PRIMARY KEY (`idGALERIA`, `dniEMPLEADO`, `FechaIni`),
  INDEX `fk_GALERIA_has_EMPLEADO_EMPLEADO1_idx` (`dniEMPLEADO` ASC) ,
  INDEX `fk_GALERIA_has_EMPLEADO_GALERIA1_idx` (`idGALERIA` ASC) ,
  CONSTRAINT `fk_GALERIA_has_EMPLEADO_GALERIA1`
    FOREIGN KEY (`idGALERIA`)
    REFERENCES `galeriaArte`.`GALERIA` (`idGALERIA`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_GALERIA_has_EMPLEADO_EMPLEADO1`
    FOREIGN KEY (`dniEMPLEADO`)
    REFERENCES `galeriaArte`.`EMPLEADO` (`DNI`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `galeriaArte`.`ORGANIZASUBASTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `galeriaArte`.`ORGANIZASUBASTA` (
  `idSUBASTA` INT NOT NULL,
  `idGALERIA` INT NOT NULL,
  `FechaInicio` DATE NOT NULL,
  `FechaFin` DATE NULL,
  PRIMARY KEY (`idSUBASTA`, `idGALERIA`, `FechaInicio`),
  INDEX `fk_SUBASTA_has_GALERIA_GALERIA1_idx` (`idGALERIA` ASC) ,
  INDEX `fk_SUBASTA_has_GALERIA_SUBASTA1_idx` (`idSUBASTA` ASC) ,
  CONSTRAINT `fk_SUBASTA_has_GALERIA_SUBASTA1`
    FOREIGN KEY (`idSUBASTA`)
    REFERENCES `galeriaArte`.`SUBASTA` (`idSUBASTA`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_SUBASTA_has_GALERIA_GALERIA1`
    FOREIGN KEY (`idGALERIA`)
    REFERENCES `galeriaArte`.`GALERIA` (`idGALERIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `galeriaArte`.`ORGANIZAEXPOSICION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `galeriaArte`.`ORGANIZAEXPOSICION` (
  `idGALERIA` INT NOT NULL,
  `idEXPOSICION` INT NOT NULL,
  `FechaInicio` DATE NOT NULL,
  `FechaFin` DATE NULL,
  PRIMARY KEY (`idGALERIA`, `idEXPOSICION`, `FechaInicio`),
  INDEX `fk_GALERIA_has_EXPOSICION_EXPOSICION1_idx` (`idEXPOSICION` ASC) ,
  INDEX `fk_GALERIA_has_EXPOSICION_GALERIA1_idx` (`idGALERIA` ASC) ,
  CONSTRAINT `fk_GALERIA_has_EXPOSICION_GALERIA1`
    FOREIGN KEY (`idGALERIA`)
    REFERENCES `galeriaArte`.`GALERIA` (`idGALERIA`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_GALERIA_has_EXPOSICION_EXPOSICION1`
    FOREIGN KEY (`idEXPOSICION`)
    REFERENCES `galeriaArte`.`EXPOSICION` (`idEXPOSICION`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

USE `galeriaArte`;

DELIMITER $$
USE `galeriaArte`$$
CREATE DEFINER= CURRENT_USER TRIGGER `galeriaArte`.`calcular_edad_artista` BEFORE INSERT ON `ARTISTA` FOR EACH ROW
BEGIN
    IF NEW.FechaNacimiento IS NOT NULL AND NEW.Edad IS NULL THEN
        SET NEW.Edad = YEAR(CURRENT_TIMESTAMP()) - YEAR(NEW.FechaNacimiento);
    END IF;
END$$

USE `galeriaArte`$$
CREATE DEFINER = CURRENT_USER TRIGGER `galeriaArte`.`check_tipos_obra` BEFORE INSERT ON `OBRA` FOR EACH ROW
BEGIN
	IF NEW.Tipo = "Escultura" AND (NEW.Superficie IS NOT NULL OR NEW.TipoPintura IS NOT NULL 
			OR NEW.Papel IS NOT NULL OR NEW.Metodo IS NOT NULL OR NEW.TipoCamara IS NOT NULL) THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Una escultura no puede tener ninguna de las siguientes propiedades: superficie, pintura, papel y/o metodo';
    END IF;
    
	IF NEW.Tipo = "Pintura" AND (NEW.Material IS NOT NULL OR NEW.TipoCamara IS NOT NULL 
			OR NEW.Papel IS NOT NULL OR NEW.Metodo IS NOT NULL OR NEW.Herramienta IS NOT NULL) THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Una pintura no puede tenerninguna de las siguientes propiedades: material, camara, papel, metodo y/o herramienta';
    END IF;
    
	IF NEW.Tipo = "Fotografia" AND (NEW.Material IS NOT NULL OR NEW.Dimensiones IS NOT NULL 
			OR NEW.Superficie IS NOT NULL OR NEW.TipoPintura IS NOT NULL OR NEW.Herramienta IS NOT NULL) THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Una fotografía no puede tener ninguna de las siguientes propiedades: material, dimensiones, pintura, herramienta y/o superficie';
    END IF;
END$$

USE `galeriaArte`$$
CREATE DEFINER = CURRENT_USER TRIGGER `galeriaArte`.`check_tipos_obraUpdate` BEFORE UPDATE ON `OBRA` FOR EACH ROW
BEGIN
	IF OLD.Tipo = "Escultura" AND (NEW.Superficie IS NOT NULL OR NEW.TipoPintura IS NOT NULL 
			OR NEW.Papel IS NOT NULL OR NEW.Metodo IS NOT NULL OR NEW.TipoCamara IS NOT NULL) THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Una escultura no puede tener ninguna de las siguientes propiedades: superficie, pintura, papel y/o metodo';
    END IF;
    
	IF OLD.Tipo = "Pintura" AND (NEW.Material IS NOT NULL OR NEW.TipoCamara IS NOT NULL 
			OR NEW.Papel IS NOT NULL OR NEW.Metodo IS NOT NULL OR NEW.Herramienta IS NOT NULL) THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Una pintura no puede tenerninguna de las siguientes propiedades: material, camara, papel, metodo y/o herramienta';
    END IF;
    
	IF OLD.Tipo = "Fotografia" AND (NEW.Material IS NOT NULL OR NEW.Dimensiones IS NOT NULL 
			OR NEW.Superficie IS NOT NULL OR NEW.TipoPintura IS NOT NULL OR NEW.Herramienta IS NOT NULL) THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Una fotografía no puede tener ninguna de las siguientes propiedades: material, dimensiones, pintura, herramienta y/o superficie';
    END IF;
END$$


USE `galeriaArte`$$
CREATE DEFINER = CURRENT_USER TRIGGER `galeriaArte`.`exclusion_especializacion_obra` BEFORE INSERT ON `OBRA` FOR EACH ROW
BEGIN
	IF NEW.Tipo <> "Escultura" AND NEW.Tipo <> "Pintura" AND NEW.Tipo <> "Fotografia" THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El tipo de obra solo puede ser Escultura, Pintura o Fotografia';
    END IF;
END$$

USE `galeriaArte`$$
CREATE DEFINER = CURRENT_USER TRIGGER `galeriaArte`.`ExclusividadObra_Muestra` BEFORE INSERT ON `MUESTRA` FOR EACH ROW
BEGIN
	DECLARE id INT;
    SELECT idOBRA INTO @id FROM OFRECE WHERE idObra = NEW.idOBRA limit 1;
	IF (@id = NEW.idObra) THEN
		 SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Condición de exclusividad entre OFRECE y MUESTRA respecto OBRA';
    END IF;
END$$

USE `galeriaArte`$$
CREATE DEFINER = CURRENT_USER TRIGGER `galeriaArte`.`ExclusividadObra_Ofrece` BEFORE INSERT ON `OFRECE` FOR EACH ROW
BEGIN
	DECLARE id INT;
    SELECT idOBRA INTO @id FROM MUESTRA WHERE idOBRA = NEW.idOBRA limit 1;
	IF (@id = NEW.idOBRA) THEN
		 SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Condición de exclusividad entre OFRECE y MUESTRA respecto OBRA';
    END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
